import re
import click
from lankit.cli.__main__ import cli

_COMMENT_RE = re.compile(r'comment="(kit:[^"]+)"')
_RECEIVED_RE = re.compile(r'received=(\d+)')


@cli.command(name="probe")
@click.option("--config", "-c", "config_path", type=click.Path(), default=None,
              metavar="PATH", help="Path to network.yml")
@click.option("--segment", "-s", type=str, default=None, metavar="NAME",
              help="Probe only this segment")
@click.option("--audit-only", is_flag=True, default=False,
              help="Skip gateway pings, run config audit only")
def probe(config_path, segment, audit_only):
    """Verify the live router matches network.yml.

    Two phases:

    \b
      Phase 1 — Config audit (no traffic)
        Compares every kit:-tagged rule lankit would generate against
        what is actually present on the router. Surfaces missing rules
        (apply didn't fully succeed) and stale rules (previous config
        not cleaned up after a segment was removed or renamed).

      Phase 2 — Gateway reachability
        Pings each segment's gateway from the router to confirm VLAN
        interfaces are up and routing is configured.

    \b
    Forward-chain note:
        Inter-segment firewall rules live in RouterOS's forward chain.
        Traffic generated by the router itself (including these probes)
        goes through the output chain — so probe cannot verify whether
        trusted→iot is actually blocked. The audit confirms the rules
        are present; it cannot confirm their effect on live traffic.
        Full traffic testing requires a physical device in each segment.

    \b
    Examples:
      lankit probe
      lankit probe --segment iot
      lankit probe --audit-only
    """
    from lankit.core.config import load, ConfigError
    from lankit.core.router import RouterConnection, RouterError
    from pathlib import Path
    from rich.console import Console
    from rich.table import Table
    from rich import box

    console = Console()

    try:
        cfg = load(Path(config_path) if config_path else None)
    except ConfigError as e:
        console.print(f"[bold red]Config error:[/bold red] {e}")
        raise SystemExit(1)

    segments = (
        {segment: cfg.segments[segment]} if segment else cfg.segments
    )
    if segment and segment not in cfg.segments:
        console.print(f"[bold red]Unknown segment:[/bold red] {segment!r}")
        raise SystemExit(1)

    console.print(f"\n[bold]Probing {cfg.household_name}[/bold] — {len(segments)} segment(s) — {cfg.router.ip}\n")

    try:
        with RouterConnection(cfg.router.ip, cfg.router.ssh_user, cfg.ssh_key) as conn:
            identity = conn.identity()
            version = conn.version()
            console.print(f"  [dim]{identity}  RouterOS {version}[/dim]\n")

            # ── Phase 1: Config audit ─────────────────────────────────────────
            console.print("[bold]Phase 1 — Configuration audit[/bold]")
            console.print("[dim]  Comparing expected kit: rules against live router config.[/dim]\n")

            expected = _build_expected_tags(cfg)
            live = _read_live_tags(conn)

            expected_set = set(expected)
            missing = sorted(expected_set - live)
            stale = sorted(t for t in live if t.startswith("kit:") and t not in expected_set)

            # Per-segment audit table
            audit_table = Table(box=box.SIMPLE_HEAD, show_lines=False, padding=(0, 1))
            audit_table.add_column("Segment", style="bold cyan", no_wrap=True)
            audit_table.add_column("VLAN", justify="right", style="dim")
            audit_table.add_column("vlan", justify="center")
            audit_table.add_column("dhcp", justify="center")
            audit_table.add_column("firewall", justify="center")
            audit_table.add_column("wifi", justify="center")

            for name, seg in cfg.segments.items():
                if segment and name != segment:
                    continue
                counts = _per_segment_counts(name, seg, cfg, expected_set, live)
                audit_table.add_row(
                    name,
                    str(seg.vlan_id),
                    _fmt(counts["vlan"]),
                    _fmt(counts["dhcp"]),
                    _fmt(counts["fw"]),
                    _fmt(counts["wifi"]) if counts["wifi"][1] > 0 else "[dim]—[/dim]",
                )

            # Global row
            global_counts = _global_counts(expected_set, live)
            audit_table.add_row(
                "[dim]global[/dim]", "[dim]—[/dim]",
                "[dim]—[/dim]",
                "[dim]—[/dim]",
                _fmt(global_counts),
                "[dim]—[/dim]",
            )

            console.print(audit_table)

            total_expected = len(expected_set)
            total_found = len(expected_set & live)
            if missing:
                console.print(f"  [yellow]{total_found}/{total_expected} rules present. Missing:[/yellow]")
                for tag in missing:
                    console.print(f"    [red]✗[/red] {tag}")
                console.print(f"\n  Run [bold]lankit apply[/bold] to push missing rules.\n")
            else:
                console.print(f"  [green]✓[/green] All {total_expected} expected rules present.\n")

            if stale:
                console.print(f"  [dim]{len(stale)} stale rule(s) on router (not in current network.yml):[/dim]")
                for tag in stale:
                    console.print(f"    [dim]~[/dim] {tag}")
                console.print(f"  [dim]Stale rules are harmless but may indicate a segment was removed.[/dim]")
                console.print(f"  [dim]They can be cleaned up manually via WinBox or SSH.[/dim]\n")

            # ── Phase 2: Gateway reachability ─────────────────────────────────
            if not audit_only:
                console.print("[bold]Phase 2 — Gateway reachability[/bold]")
                console.print("[dim]  Router-sourced pings (output chain). Confirms VLAN interfaces[/dim]")
                console.print("[dim]  are up — does NOT test inter-segment firewall rules.[/dim]\n")

                gw_table = Table(box=box.SIMPLE_HEAD, show_lines=False, padding=(0, 1))
                gw_table.add_column("Segment", style="bold cyan", no_wrap=True)
                gw_table.add_column("Gateway", style="dim")
                gw_table.add_column("Result", justify="center")
                gw_table.add_column("", style="dim")

                gw_pass = gw_fail = 0
                for name, seg in cfg.segments.items():
                    if segment and name != segment:
                        continue
                    ok, detail = _ping_gateway(conn, seg.gateway)
                    if ok:
                        gw_pass += 1
                        gw_table.add_row(name, seg.gateway, "[green]✓[/green]", detail)
                    else:
                        gw_fail += 1
                        gw_table.add_row(name, seg.gateway, "[red]✗[/red]", detail)

                console.print(gw_table)

                total_gw = gw_pass + gw_fail
                if gw_fail:
                    console.print(f"  [yellow]{gw_pass}/{total_gw} gateways reachable.[/yellow]")
                    console.print(f"  Unreachable gateways suggest missing VLAN interfaces — check 01-vlans.rsc was applied.\n")
                else:
                    console.print(f"  [green]✓[/green] All {total_gw} gateways reachable.\n")

            # ── Bridge IP-firewall check ──────────────────────────────────────
            use_ip_fw = _bridge_use_ip_firewall(conn)
            console.print("[dim]─────────────────────────────────────────────────────[/dim]")
            if use_ip_fw is False:
                console.print(
                    "[yellow]⚠[/yellow]  [bold]Bridge IP firewall is off[/bold] "
                    "([dim]use-ip-firewall=no[/dim])"
                )
                console.print(
                    "   Hosts on the [bold]same VLAN[/bold] exchange bridged frames "
                    "that bypass the IP forward chain entirely."
                )
                console.print(
                    "   The rules above are deployed and protect [bold]inter-segment[/bold] "
                    "traffic, but probe cannot verify intra-VLAN host-to-host reachability "
                    "from the router."
                )
                console.print(
                    "   To test: SSH to a host in a segment and ping another host in "
                    "[bold]the same segment[/bold].\n"
                )
            else:
                console.print("[dim]Forward-chain verification (inter-segment firewall)[/dim]")
                console.print("[dim]requires a physical device in each segment. The[/dim]")
                console.print("[dim]matrix above shows intended policy; probe confirmed[/dim]")
                console.print("[dim]the rules are deployed, not that they work as intended.[/dim]")
                console.print()
            console.print("[dim]Run: lankit matrix  to review the expected policy.[/dim]\n")

    except RouterError as e:
        console.print(f"[bold red]Router error:[/bold red] {e}")
        raise SystemExit(1)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_expected_tags(cfg) -> list[str]:
    """Complete list of kit: tags lankit would generate for this config."""
    tags = []

    dns = cfg.hosts.get("dns_server")
    dns_segment = dns.segment if dns else None

    for name, seg in cfg.segments.items():
        # VLAN
        tags += [f"kit:vlan:{name}:interface", f"kit:vlan:{name}:bridge"]
        # DHCP
        tags += [
            f"kit:dhcp:{name}:address",
            f"kit:dhcp:{name}:pool",
            f"kit:dhcp:{name}:server",
            f"kit:dhcp:{name}:network",
        ]
        # Firewall: LAN member + address list
        tags += [f"kit:fw:{name}:lan-member", f"kit:fw:{name}:address-list"]
        # Firewall: client isolation
        if seg.client_isolation:
            tags.append(f"kit:fw:{name}:isolation")
        # Firewall: DNS permits
        if seg.dns != "none":
            tags += [f"kit:fw:{name}>dns:permit-udp", f"kit:fw:{name}>dns:permit-tcp"]
        # Firewall: internet egress
        if seg.internet in ["full", "egress_only"]:
            tags.append(f"kit:fw:{name}:egress")
        # WiFi
        if seg.has_wifi:
            tags.append(f"kit:wifi:{name}:security")
            if "5ghz" in seg.wifi_bands:
                tags += [f"kit:wifi:{name}:ap-5g", f"kit:wifi:{name}:bridge-5g"]
            if "2ghz" in seg.wifi_bands:
                tags += [f"kit:wifi:{name}:ap-2g", f"kit:wifi:{name}:bridge-2g"]

    # Inter-segment permits
    for src, perm in cfg.permissions.items():
        for dst in perm.can_reach:
            tags.append(f"kit:fw:{src}>{dst}:permit")

    # Global
    tags += [
        "kit:fw:all:local-rfc1918",
        "kit:fw:all:local-flat",
        "kit:fw:all:mark-internet",
        "kit:fw:all:default-deny",
        "kit:fw:all:fasttrack-internet",
        "kit:nat:all:masquerade",
        "kit:vlan:legacy:flat",
        "kit:dhcp:dns-server:lease",
    ]

    return tags


def _read_live_tags(conn) -> set[str]:
    """Read all kit: tagged comments from the live router."""
    commands = [
        "/interface vlan print detail without-paging",
        "/interface bridge vlan print detail without-paging",
        "/interface bridge port print detail without-paging",
        "/interface list member print detail without-paging",
        "/ip address print detail without-paging",
        "/ip pool print detail without-paging",
        "/ip dhcp-server print detail without-paging",
        "/ip dhcp-server network print detail without-paging",
        "/ip dhcp-server lease print detail without-paging",
        "/ip firewall address-list print detail without-paging",
        "/ip firewall filter print detail without-paging",
        "/ip firewall mangle print detail without-paging",
        "/ip firewall nat print detail without-paging",
    ]
    wifi_commands = [
        "/interface wifi security print detail without-paging",
        "/interface wifi print detail without-paging",
    ]

    found: set[str] = set()
    for cmd in commands:
        out, _ = conn.run_tolerant(cmd)
        found.update(_COMMENT_RE.findall(out))
    for cmd in wifi_commands:
        out, err = conn.run_tolerant(cmd)
        if not err:
            found.update(_COMMENT_RE.findall(out))

    return found


def _per_segment_counts(name, seg, cfg, expected_set, live):
    """Count expected vs found tags per category for a segment."""
    def count(prefix):
        exp = [t for t in expected_set if t.startswith(prefix)]
        found = sum(1 for t in exp if t in live)
        return found, len(exp)

    return {
        "vlan": count(f"kit:vlan:{name}:"),
        "dhcp": count(f"kit:dhcp:{name}:"),
        "fw":   (
            sum(1 for t in expected_set
                if (t.startswith(f"kit:fw:{name}") or f">{name}:" in t or f"{name}>" in t)
                and t in live),
            len([t for t in expected_set
                 if t.startswith(f"kit:fw:{name}") or f">{name}:" in t or f"{name}>" in t]),
        ),
        "wifi": count(f"kit:wifi:{name}:"),
    }


def _global_counts(expected_set, live):
    global_tags = [t for t in expected_set if ":all:" in t or t in {
        "kit:vlan:legacy:flat", "kit:dhcp:dns-server:lease",
    }]
    found = sum(1 for t in global_tags if t in live)
    return found, len(global_tags)


def _fmt(counts: tuple[int, int]) -> str:
    found, total = counts
    if total == 0:
        return "[dim]—[/dim]"
    if found == total:
        return f"[green]✓ {found}[/green]"
    return f"[red]✗ {found}/{total}[/red]"


def _ping_gateway(conn, gateway: str) -> tuple[bool, str]:
    out, _ = conn.run_tolerant(f"/ping address={gateway} count=3")
    m = _RECEIVED_RE.search(out)
    received = int(m.group(1)) if m else 0
    return received > 0, f"{received}/3 packets"


def _bridge_use_ip_firewall(conn) -> bool | None:
    """Return True/False for use-ip-firewall bridge setting, None on error."""
    out, err = conn.run_tolerant("/interface bridge settings print")
    if err:
        return None
    m = re.search(r"use-ip-firewall:\s*(yes|no)", out)
    if not m:
        return None
    return m.group(1) == "yes"
